import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useState } from 'react'
import { toast } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [name, setName] = useState('');
  const [number, setNumber] = useState('');
  const [email, setEmail] = useState('');
  const [emailError, setEmailError] = useState('');
  const [phoneNumberError, setPhoneNumberError] = useState('');
  const validateEmail = (email) => {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    return emailRegex.test(email);
  };
  const validatePhoneNumber = (phoneNumber) => {
    const phoneNumberRegex = /^\d{10}$/;
    return phoneNumberRegex.test(phoneNumber);
  };
  const handleSubmit = async (e)=>{
    e.preventDefault()
    if (!validateEmail(email)) {
      setEmailError('Please enter a valid email address');
      
    } else {
      setEmailError('');
    }
    if (!validatePhoneNumber(number)) {
      setPhoneNumberError('Please enter a valid phone number');
      
    } else {
      setPhoneNumberError('');
    }
    if (!validateEmail(email) || !validatePhoneNumber(number) ){
      return
    }
    const now = new Date()
    const data = {
      name: name,
        phonenumber: number,
        email: email,
        date: now
    }
    const response = await fetch('/api/handleSubmit',{
      method : "POST",
      body: JSON.stringify(data)
    })
    .then((response)=>{
      if(!response.ok){
      toast.error("Something went wrong");
      }
      else{
        toast.success('Thanks for booking');
      }
    })
    

  }

  return (
    <>
      <Head>
        <title>Car Detailing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen">
        <div className='flex justify-center items-center '>
        <h1 className='text-5xl font-bold'>Adam and Yusufs Ramadan Car Detailing</h1>
        </div>
        <div className='flex w-full h-1/2'>

        </div>
        <div className='flex justify-center items-center mb-2'>
        <h1 className='text-2xl font-bold'>Book with us</h1>
        </div>
        <div className='flex items-center justify-center'>
        <form onSubmit={handleSubmit} className = "flex flex-col gap-4 w-[20rem]">
        <input type="text" required value={name} onChange = {(e)=>setName(e.target.value)} placeholder="Name" className="input input-bordered w-full max-w-xs" />
        {phoneNumberError && <span className="text-red-600">{phoneNumberError}</span>}
        <input type="text" required value={number} onChange = {(e)=>setNumber(e.target.value)} placeholder="Phone-Number"  className="input input-bordered w-full max-w-xs" />
        {emailError && <span className="text-red-600">{emailError}</span>}
        <input type="text" required value={email} onChange = {(e)=>setEmail(e.target.value)} placeholder="Email" className="input input-bordered w-full max-w-xs" />
        <button className='btn' type='submit'>Confirm booking</button>
        </form>
        </div>
      </main>
    </>
  )
}
